ALTER TABLE IF EXISTS bid
DROP
CONSTRAINT FK_BidItem;

ALTER TABLE IF EXISTS bid
ALTER
COLUMN item_id TYPE VARCHAR(50);

ALTER TABLE IF EXISTS bid
ALTER
COLUMN id TYPE VARCHAR(50);

ALTER TABLE IF EXISTS item
ALTER
COLUMN id TYPE VARCHAR(50);

ALTER TABLE IF EXISTS bid
    ADD CONSTRAINT FK_BidItem
    FOREIGN KEY (item_id) REFERENCES item(id);



